APP_NAME="ScoreLoan"
SHORT_NAME="ScoreLoan"
DESCRIPTION="Get instant loan approval in just 2 minutes! ScoreLoan is AI based credit marketplace which offers instant loan and personal loans up to 5 lakh."
THEME_COLOR="#0175C2"
BACKGROUND_COLOR="#0175C2"
